path: C:\Users\trung\OneDrive - UTS\UTS University\Sem 2\Deep Learning\Assignment 3\data
train: images\train
val: images\val

names:
  0: uts_id
  1: other_id
  2: id_number
  3: id_first_name
  4: id_last_name
  5: unique_pattern
  6: id_logo